// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.5
// source: pb/federated.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederatedLearning_SendModelParameters_FullMethodName   = "/federated.FederatedLearning/SendModelParameters"
	FederatedLearning_GetGlobalParameters_FullMethodName   = "/federated.FederatedLearning/GetGlobalParameters"
	FederatedLearning_UpdateModelParameters_FullMethodName = "/federated.FederatedLearning/UpdateModelParameters"
)

// FederatedLearningClient is the client API for FederatedLearning service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The service definition for federated learning.
type FederatedLearningClient interface {
	// Clients send their model parameters to the server.
	SendModelParameters(ctx context.Context, in *ModelParameters, opts ...grpc.CallOption) (*Empty, error)
	// Server sends the global model parameters to the clients.
	GetGlobalParameters(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelParameters, error)
	UpdateModelParameters(ctx context.Context, in *ModelParameters, opts ...grpc.CallOption) (*Response, error)
}

type federatedLearningClient struct {
	cc grpc.ClientConnInterface
}

func NewFederatedLearningClient(cc grpc.ClientConnInterface) FederatedLearningClient {
	return &federatedLearningClient{cc}
}

func (c *federatedLearningClient) SendModelParameters(ctx context.Context, in *ModelParameters, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, FederatedLearning_SendModelParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedLearningClient) GetGlobalParameters(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ModelParameters, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelParameters)
	err := c.cc.Invoke(ctx, FederatedLearning_GetGlobalParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedLearningClient) UpdateModelParameters(ctx context.Context, in *ModelParameters, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FederatedLearning_UpdateModelParameters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederatedLearningServer is the server API for FederatedLearning service.
// All implementations must embed UnimplementedFederatedLearningServer
// for forward compatibility.
//
// The service definition for federated learning.
type FederatedLearningServer interface {
	// Clients send their model parameters to the server.
	SendModelParameters(context.Context, *ModelParameters) (*Empty, error)
	// Server sends the global model parameters to the clients.
	GetGlobalParameters(context.Context, *Empty) (*ModelParameters, error)
	UpdateModelParameters(context.Context, *ModelParameters) (*Response, error)
	mustEmbedUnimplementedFederatedLearningServer()
}

// UnimplementedFederatedLearningServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederatedLearningServer struct{}

func (UnimplementedFederatedLearningServer) SendModelParameters(context.Context, *ModelParameters) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendModelParameters not implemented")
}
func (UnimplementedFederatedLearningServer) GetGlobalParameters(context.Context, *Empty) (*ModelParameters, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGlobalParameters not implemented")
}
func (UnimplementedFederatedLearningServer) UpdateModelParameters(context.Context, *ModelParameters) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModelParameters not implemented")
}
func (UnimplementedFederatedLearningServer) mustEmbedUnimplementedFederatedLearningServer() {}
func (UnimplementedFederatedLearningServer) testEmbeddedByValue()                           {}

// UnsafeFederatedLearningServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederatedLearningServer will
// result in compilation errors.
type UnsafeFederatedLearningServer interface {
	mustEmbedUnimplementedFederatedLearningServer()
}

func RegisterFederatedLearningServer(s grpc.ServiceRegistrar, srv FederatedLearningServer) {
	// If the following call pancis, it indicates UnimplementedFederatedLearningServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederatedLearning_ServiceDesc, srv)
}

func _FederatedLearning_SendModelParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).SendModelParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLearning_SendModelParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).SendModelParameters(ctx, req.(*ModelParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedLearning_GetGlobalParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).GetGlobalParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLearning_GetGlobalParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).GetGlobalParameters(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedLearning_UpdateModelParameters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedLearningServer).UpdateModelParameters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FederatedLearning_UpdateModelParameters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedLearningServer).UpdateModelParameters(ctx, req.(*ModelParameters))
	}
	return interceptor(ctx, in, info, handler)
}

// FederatedLearning_ServiceDesc is the grpc.ServiceDesc for FederatedLearning service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederatedLearning_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "federated.FederatedLearning",
	HandlerType: (*FederatedLearningServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendModelParameters",
			Handler:    _FederatedLearning_SendModelParameters_Handler,
		},
		{
			MethodName: "GetGlobalParameters",
			Handler:    _FederatedLearning_GetGlobalParameters_Handler,
		},
		{
			MethodName: "UpdateModelParameters",
			Handler:    _FederatedLearning_UpdateModelParameters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/federated.proto",
}
